services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - readability-service
    restart: unless-stopped

  readability-service:
    build:
      context: ./readability-service
      dockerfile: Dockerfile
    env_file:
      - ./readability-service/.env
    restart: unless-stopped
